
DATA_DIR = "./data"
MIMIC_PATH = "data/mimic-iv-ext-bhc-labeled-clinical-notes-dataset-for-hospital-course-summarization-1.2.0/mimic-iv-bhc.csv"
NOTE_DISCHARGE_PATH = "data/mimic-iv-note-deidentified-free-text-clinical-notes-2.2/note/discharge.csv.gz"
CACHE_DIR = "data/cache"

DATASET = "MIMIC_DISPOSITION"
NUM_CLASSES = 6
NUM_CLIENTS = 20

PUBLIC_SIZE = 0 

BATCH_SIZE = 8
MAX_LENGTH = 128

NUM_ROUNDS = 2
EPOCHS_PER_ROUND = 1
LEARNING_RATE = 2e-5
SGD_MOMENTUM = 0.9
JOIN_RATIO = 0.2

LR_DECAY_STEP = 20
LR_DECAY_GAMMA = 0.9

MODEL_TYPES = ["clinical_bert_frozen", "clinical_bert_ft2", "clinical_bert_ft4"]
FEATURE_DIM = 128

PROTOTYPE_WEIGHT = 1.0
PROTOTYPE_WARMUP_RATE = 0.01

N_ALIGNMENT = 100
N_LOGITS_MATCHING_ROUND = 1
N_PRIVATE_TRAINING_ROUND = 1
PRIVATE_TRAINING_BATCHSIZE = 16

FEDTGP_SERVER_EPOCHS = 100
FEDTGP_SERVER_BATCH_SIZE = 16
FEDTGP_MARGIN_THRESHOLD = 5.0

FEDPAGR_BETA = 0.5 
FEDPAGR_LAMBDA_S = 1.0 
FEDPAGR_LAMBDA_T = 0.5 
FEDPAGR_MARGIN = 0.3 
FEDPAGR_REFINE_LR = 0.01 
FEDPAGR_REFINE_STEPS = 5 
FEDPAGR_ENTROPY_WEIGHT = 0.01 

CHECKPOINT_FREQ = 10
EVAL_FREQ = 20
SEED = 42

FINAL_AVERAGE_WINDOW = 5
ENABLE_ENSEMBLE_EVAL = False
ENABLE_CLIENT_GLOBAL_EVAL = False

CONVERGENCE_WINDOW = 10
CONVERGENCE_THRESHOLD = 0.001

OUTPUT_DIR = "./fl_plots_clinical"
EXPERIMENT_NAME = "mimic_clinical_fl"

USE_CUDA = True

DATALOADER_NUM_WORKERS = 0
DATALOADER_PIN_MEMORY = True
DATALOADER_PERSISTENT_WORKERS = True

USE_AMP = True

USE_MULTI_GPU = True
GPU_IDS = [0, 1]

CACHE_TRANSFORMS = False
TRANSFORM_CACHE_DIR = "./data/transform_cache"

LABEL_HETEROGENEITY = "dirichlet" 
DIRICHLET_ALPHA = 0.1

DATA_HETEROGENEITY = "none" 
DATA_TRANSFORM_TYPES = [] 
DATA_TRANSFORM_ASSIGNMENT = None
